from app.models.role import Role
from app.models.permission import Permission
from app.models.role_permission import RolePermission
from app.models.user import User
from app.models.refresh_token import RefreshToken
from app.models.note import Note
from app.models.book import Book
from app.models.bookmark import Bookmark
from app.models.current_affair import CurrentAffair
from app.models.current_affair_category import CurrentAffairCategory
from app.models.progress import Progress
from app.models.quiz import Quiz
from app.models.question import Question
from app.models.quiz_attempt import QuizAttempt
from app.models.setting import Setting