import {
  BookOpen,
  NotebookPen,
  Newspaper,
  Brain,
  Calculator,
  Lightbulb,
  PlayCircle,
  FileText,
  ClipboardCheck,
  Target,
  BarChart3,
  Bookmark,
} from "lucide-react";

export const quickActions = [
  {
    title: "TN Books",
    icon: BookOpen,
    href: "/books",
    color: "bg-violet-100",
    iconColor: "text-violet-600",
  },
  {
    title: "Notes",
    icon: NotebookPen,
    href: "/notes",
    color: "bg-green-100",
    iconColor: "text-green-600",
  },
  {
    title: "Current Affairs",
    icon: Newspaper,
    href: "/current-affairs",
    color: "bg-red-100",
    iconColor: "text-red-600",
  },
  {
    title: "Daily Quiz",
    icon: Brain,
    href: "/quiz",
    color: "bg-blue-100",
    iconColor: "text-blue-600",
  },
  {
    title: "Maths Tricks",
    icon: Calculator,
    href: "/maths",
    color: "bg-orange-100",
    iconColor: "text-orange-600",
  },
  {
    title: "Interesting Facts",
    icon: Lightbulb,
    href: "/facts",
    color: "bg-yellow-100",
    iconColor: "text-yellow-600",
  },
  {
    title: "YouTube",
    icon: PlayCircle,
    href: "/youtube",
    color: "bg-pink-100",
    iconColor: "text-pink-600",
  },
  {
    title: "Previous Papers",
    icon: FileText,
    href: "/papers",
    color: "bg-cyan-100",
    iconColor: "text-cyan-600",
  },
  {
    title: "Mock Tests",
    icon: ClipboardCheck,
    href: "/mock-tests",
    color: "bg-indigo-100",
    iconColor: "text-indigo-600",
  },
  {
    title: "Custom Test",
    icon: Target,
    href: "/custom-test",
    color: "bg-emerald-100",
    iconColor: "text-emerald-600",
  },
  {
    title: "Performance",
    icon: BarChart3,
    href: "/performance",
    color: "bg-lime-100",
    iconColor: "text-lime-600",
  },
  {
    title: "Bookmarks",
    icon: Bookmark,
    href: "/bookmarks",
    color: "bg-rose-100",
    iconColor: "text-rose-600",
  },
];