import { Book } from "@/types/book";

export const BOOKS: Book[] = [
  {
    id: 1,
    title: "6th Tamil",
    subject: "Tamil",
    standard: 6,
    medium: "Tamil",
    cover: "/books/tamil6.jpg",
    pdf: "/pdfs/tamil6.pdf",
    description: "Tamil Nadu State Board Class 6 Tamil Book",
    pages: 240,
    rating: 4.8,
    downloads: 12560,
  },
  {
    id: 2,
    title: "6th Science",
    subject: "Science",
    standard: 6,
    medium: "English",
    cover: "/books/science6.jpg",
    pdf: "/pdfs/science6.pdf",
    description: "Tamil Nadu State Board Class 6 Science Book",
    pages: 220,
    rating: 4.7,
    downloads: 10120,
  },
  {
    id: 3,
    title: "7th History",
    subject: "History",
    standard: 7,
    medium: "Tamil",
    cover: "/books/history7.jpg",
    pdf: "/pdfs/history7.pdf",
    description: "Tamil Nadu State Board Class 7 History Book",
    pages: 198,
    rating: 4.9,
    downloads: 8930,
  },
  {
    id: 4,
    title: "10th Polity",
    subject: "Polity",
    standard: 10,
    medium: "Tamil",
    cover: "/books/polity10.jpg",
    pdf: "/pdfs/polity10.pdf",
    description: "TNPSC Polity Reference Book",
    pages: 310,
    rating: 4.9,
    downloads: 15400,
  },
];