"""add user security fields

Revision ID: 665444606a94
Revises: d597b45b8f6f
Create Date: 2026-07-18 15:27:36.243713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '665444606a94'
down_revision: Union[str, Sequence[str], None] = 'd597b45b8f6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_answers')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_quiz_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_table('quiz_attempts')
    op.alter_column('books', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('books', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('current_affairs', sa.Column('month', sa.String(length=20), nullable=True))
    op.add_column('current_affairs', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('current_affairs', sa.Column('is_breaking', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('is_locked', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('reset_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('reset_token_expiry', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('verification_token', sa.String(length=255), nullable=True))
    # Convert role to enum
    op.execute("""
    ALTER TABLE users
    ALTER COLUMN role
    TYPE user_roles
    USING role::user_roles;
    """)

    # Convert language to enum
    op.execute("""
    ALTER TABLE users
    ALTER COLUMN language
    TYPE language_types
    USING language::language_types;
    """)

    # Convert theme to enum
    op.execute("""
    ALTER TABLE users
    ALTER COLUMN theme
    TYPE theme_types
    USING theme::theme_types;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'theme',
               existing_type=sa.Enum('light', 'dark', name='theme_types'),
               type_=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('users', 'language',
               existing_type=sa.Enum('Tamil', 'English', name='language_types'),
               type_=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('admin', 'user', name='user_roles'),
               type_=sa.VARCHAR(length=30),
               nullable=True)
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'reset_token_expiry')
    op.drop_column('users', 'reset_token')
    op.drop_column('users', 'is_locked')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('current_affairs', 'is_breaking')
    op.drop_column('current_affairs', 'year')
    op.drop_column('current_affairs', 'month')
    op.alter_column('books', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('books', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_table('quiz_attempts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quiz_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_questions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('correct_answers', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wrong_answers', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('skipped_answers', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time_taken', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('quiz_attempts_quiz_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('quiz_attempts_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('quiz_attempts_pkey'))
    )
    op.create_table('questions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('quiz_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('standard', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('option_a', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('option_b', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('option_c', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('option_d', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('correct_answer', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('explanation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('marks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('questions_quiz_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('questions_pkey'))
    )
    op.create_index(op.f('ix_questions_quiz_id'), 'questions', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_table('quiz_answers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('attempt_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('selected_option', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('is_correct', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.id'], name=op.f('quiz_answers_attempt_id_fkey')),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('quiz_answers_question_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('quiz_answers_pkey'))
    )
    # ### end Alembic commands ###
