"use client";

import {
  CalendarDays,
  BookOpen,
  Clock,
  Flame,
} from "lucide-react";

import { RevisionTask } from "@/services/adaptiveLearningService";

interface Props {
  tasks: RevisionTask[];
}

export default function RevisionPlanner({
  tasks,
}: Props) {
  function getPriorityBadge(priority: string) {
    switch (priority.toLowerCase()) {
      case "high":
        return "bg-red-100 text-red-700 border-red-200";

      case "medium":
        return "bg-yellow-100 text-yellow-700 border-yellow-200";

      case "low":
        return "bg-green-100 text-green-700 border-green-200";

      default:
        return "bg-gray-100 text-gray-700 border-gray-200";
    }
  }

  return (
    <div className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm">

      {/* Header */}

      <div className="mb-6 flex items-center gap-3">
        <CalendarDays className="h-7 w-7 text-blue-600" />

        <div>
          <h2 className="text-xl font-bold text-gray-800">
            Revision Planner
          </h2>

          <p className="text-sm text-gray-500">
            Personalized revision schedule generated by AI.
          </p>
        </div>
      </div>

      {/* Empty State */}

      {tasks.length === 0 ? (
        <div className="rounded-xl border border-green-200 bg-green-50 p-6 text-center">
          <p className="font-medium text-green-700">
            🎉 Your revision plan is complete.
          </p>
        </div>
      ) : (
        <div className="space-y-5">

          {tasks.map((task, index) => (
            <div
              key={`${task.subject}-${task.topic}-${index}`}
              className="rounded-xl border border-gray-200 p-5 transition-all hover:shadow-md"
            >

              {/* Top Row */}

              <div className="mb-4 flex flex-col gap-4 md:flex-row md:items-center md:justify-between">

                <div className="flex items-center gap-3">
                  <BookOpen className="h-5 w-5 text-blue-600" />

                  <div>
                    <h3 className="font-semibold text-gray-800">
                      {task.subject}
                    </h3>

                    <p className="text-sm text-gray-500">
                      {task.topic}
                    </p>
                  </div>
                </div>

                <span
                  className={`inline-flex items-center rounded-full border px-3 py-1 text-sm font-semibold ${getPriorityBadge(
                    task.priority
                  )}`}
                >
                  <Flame className="mr-1 h-4 w-4" />
                  {task.priority}
                </span>

              </div>

              {/* Details */}

              <div className="grid gap-4 md:grid-cols-2">

                <div className="flex items-center gap-2 rounded-lg bg-gray-50 p-3">
                  <CalendarDays className="h-5 w-5 text-blue-600" />

                  <div>
                    <p className="text-xs uppercase text-gray-500">
                      Scheduled
                    </p>

                    <p className="font-medium text-gray-700">
                      {task.day}
                    </p>
                  </div>
                </div>

                <div className="flex items-center gap-2 rounded-lg bg-gray-50 p-3">
                  <Clock className="h-5 w-5 text-green-600" />

                  <div>
                    <p className="text-xs uppercase text-gray-500">
                      Study Time
                    </p>

                    <p className="font-medium text-gray-700">
                      {task.estimated_minutes} minutes
                    </p>
                  </div>
                </div>

              </div>

            </div>
          ))}

        </div>
      )}

    </div>
  );
}